[build]
  command = "npm run build"
  publish = "dist"
  functions = "supabase/functions"
  base = "/"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)supabase/functions'"

[build.environment]
  NODE_VERSION = "20"
  GITHUB_REPOSITORY = "ProjectSpartanSurvey"

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers to enable security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:;"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge functions config
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Plugin configurations
[build.plugins]

[plugin.typescript]
  package = "@netlify/plugin-typescript"
  [plugin.typescript.inputs]
    strict = true

[plugin.lighthouse]
  package = "@netlify/plugin-lighthouse"
  [plugin.lighthouse.inputs]
    output_path = "reports/lighthouse.html"

# Repository settings
[context.production]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

# Development settings
[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  command = "npm run dev"

# GitHub configuration
[template.environment]
  GITHUB_REPO = "ProjectSpartanSurvey"
  GITHUB_TOKEN = "required"